# Generated by Django 2.2.5 on 2019-11-06 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Id'),
        ),
    ]
