# Generated by Django 2.2.5 on 2019-11-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='name',
            field=models.CharField(max_length=25, verbose_name='name'),
        ),
    ]
