# Generated by Django 2.2.5 on 2019-11-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20191106_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
    ]
